#!/usr/bin/env python3
"""Pin the script-arg dataclass field surfaces.

The expectation below is a per-class map of ``dataclasses.fields()`` name → default repr
(``factory:<value>`` for default_factory fields). Rebasing a class onto the shared mixins
(ConversationRenderArguments / GenerationEvalArguments / PromptDatasetArguments /
ChunkedLogprobsArguments) must not add, drop, or re-default a single field on any class —
any drift fails here. Field ORDER and metadata/type spellings are deliberately not pinned.

Usage:
    python tests/cpu/config/test_args_field_pin.py
"""

import dataclasses
import importlib
import pkgutil
import sys
from unittest import mock

import pytest

import src.args
from src import env
from src.args.common_script_args import CommonScriptArguments


def _script_argument_classes() -> dict[str, type]:
    """Every script-argument dataclass under ``src/args/``, by name — derived, so a new one is pinned or fails."""
    found = {CommonScriptArguments.__name__: CommonScriptArguments}
    for module_info in pkgutil.iter_modules(src.args.__path__):
        module = importlib.import_module(f"src.args.{module_info.name}")
        for name, obj in vars(module).items():
            if isinstance(obj, type) and obj.__module__ == module.__name__ and issubclass(obj, CommonScriptArguments):
                found[name] = obj
    return found


_CLASSES = _script_argument_classes()

# Generated from pre-refactor main (see module docstring). Do NOT regenerate casually: an
# intentional field change must be edited here explicitly, with the diff called out in review.
_EXPECTED = {
    "CLFScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "text_field": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "CommonScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "DPOScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "generate_eval_examples": "True",
        "generation_max_prompt_length": "512",
        "images_field": "None",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_eval_examples": "50",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "DistillScriptArguments": {
        "added_special_tokens": "None",
        "assistant_message_template": "None",
        "bos_token": "None",
        "chat_template": "None",
        "conversation_field": "'messages'",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "images_field": "None",
        "interleaved_thinking": "False",
        "log_decoded_samples": "False",
        "model_supports_system_role": "True",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "system_prompt": "None",
        "teacher_model": "None",
        "teacher_model_revision": "None",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "train_on_completions_only": "True",
        "unfreeze_layers_patterns": "None",
    },
    "EmbeddingScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "EnvironmentalGRPOScriptArguments": {
        "added_special_tokens": "None",
        "answer_field": "'answer'",
        "bos_token": "None",
        "chat_template": "None",
        "context_fields": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "log_decoded_samples": "False",
        "max_prompt_length": "None",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "prompt_field": "'prompt'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "KTOScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "completion_field": "'completion'",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "images_field": "None",
        "label_field": "'label'",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "OfflineGRPOScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "generate_eval_examples": "True",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_eval_examples": "50",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "RLVROnlineGRPOScriptArguments": {
        "accuracy_reward_weight": "1.0",
        "added_special_tokens": "None",
        "advantage_hard_group_threshold": "0.5",
        "advantage_mode": "'mean'",
        "advantage_neg_scale": "0.4",
        "advantage_pos_scale": "1.0",
        "advantage_quantile": "0.4",
        "answer_field": "'answer'",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "drop_degenerate_groups": "False",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "format_pattern": "'<think>.*?</think>\\\\s*<answer>.*?</answer>'",
        "format_reward_weight": "0.5",
        "freeze_layers_patterns": "None",
        "log_decoded_samples": "False",
        "max_prompt_length": "None",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "opd_positive_advantage_only": "True",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "prompt_field": "'prompt'",
        "reasoning_effort": "None",
        "report_mfu_diagnostics": "False",
        "rlrr_correctness_clip": "True",
        "rlrr_correctness_threshold": "0.5",
        "rlrr_lambda": "2048.0",
        "rlrr_length_rerank": "True",
        "rlrr_mode": "'hrr'",
        "rlrr_std_normalize": "False",
        "rlrr_tau": "0.1",
        "rlrr_xi_neg": "-0.001",
        "rlrr_xi_pos": "0.001",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "scale_rewards_std_floor": "0.0",
        "sdpg_beta_base": "1.0",
        "sdpg_beta_decay_steps": "0",
        "sdpg_beta_warmup_steps": "0",
        "sdpg_hint_template": (
            "'\\n[Hint] The correct answer is: {answer}. Do NOT state that you were given the answer.\\n'"
        ),
        "sdpg_loss": "'reverse_kl'",
        "sdpg_temperature": "1.0",
        "system_prompt": "None",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
        "use_accuracy_reward": "True",
        "use_chunked_grpo_logprobs": "False",
        "use_format_reward": "False",
        "use_rlrr": "False",
        "use_sdpg": "False",
    },
    "RMScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "images_field": "None",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "SFTScriptArguments": {
        "added_special_tokens": "None",
        "assistant_message_template": "None",
        "bos_token": "None",
        "chat_template": "None",
        "conversation_field": "'prompt'",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "generate_eval_examples": "False",
        "images_field": "None",
        "interleaved_thinking": "False",
        "log_decoded_samples": "False",
        "model_supports_system_role": "True",
        "moe_balancing": "'auto'",
        "num_eval_examples": "50",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "system_prompt": "None",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "train_on_completions_only": "True",
        "train_on_last_assistant_only": "False",
        "unfreeze_layers_patterns": "None",
    },
    "SMPOScriptArguments": {
        "added_special_tokens": "None",
        "bos_token": "None",
        "chat_template": "None",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "generate_eval_examples": "True",
        "log_decoded_samples": "False",
        "moe_balancing": "'auto'",
        "num_eval_examples": "50",
        "num_full_model_params": "None",
        "pad_token": "None",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "unfreeze_layers_patterns": "None",
    },
    "SelfDistillationArguments": {
        "added_special_tokens": "None",
        "assistant_message_template": "None",
        "bos_token": "None",
        "chat_template": "None",
        "confidence_field": "None",
        "confidence_power": "4.0",
        "confidence_weight_opd": "True",
        "conversation_field": "'prompt'",
        "dataset": "'/path/to/dataset'",
        "dataset_ratio": "None",
        "enable_efficiency_metrics": "False",
        "enable_moe_metrics": "True",
        "enable_torch_profiler": "False",
        "eos_token": "None",
        "force_chat_template": "False",
        "freeze_layers_patterns": "None",
        "generate_eval_examples": "False",
        "images_field": "None",
        "interleaved_thinking": "False",
        "log_decoded_samples": "False",
        "model_supports_system_role": "True",
        "moe_balancing": "'auto'",
        "num_eval_examples": "50",
        "num_full_model_params": "None",
        "opd_exclude_eos": "True",
        "pad_token": "None",
        "privileged_solution_field": "'solution'",
        "profiler_active": "3",
        "profiler_output_dir": "factory:'<data_root>/profiling/torch'",
        "profiler_ranks": "'0'",
        "profiler_record_memory_snapshot": "False",
        "profiler_wait": "5",
        "profiler_warmup": "1",
        "project_name": "'default-project'",
        "reference_kl_coef": "0.0",
        "reference_kl_loss": "'unnormalized_kl'",
        "reference_model_name_or_path": "None",
        "report_mfu_diagnostics": "False",
        "router_balancing_rate": "0.001",
        "save_completions": "True",
        "sdpg_answer_field": "'answer'",
        "sdpg_beta_base": "1.0",
        "sdpg_beta_decay_steps": "0",
        "sdpg_beta_warmup_steps": "0",
        "sdpg_hint_template": (
            "'\\n[Hint] The correct answer is: {answer}. Do NOT state that you were given the answer.\\n'"
        ),
        "sdpg_loss": "'reverse_kl'",
        "sdpg_temperature": "1.0",
        "system_prompt": "None",
        "test_size": "None",
        "tokenizer_backend": "'hf'",
        "tools_field": "None",
        "train_on_completions_only": "True",
        "train_on_last_assistant_only": "False",
        "unfreeze_layers_patterns": "None",
    },
}


def _field_defaults(cls):
    """Field name → default repr, with the toolkit scratch root pinned to ``<data_root>``.

    ``default_factory`` paths (``profiler_output_dir``) are built by ``env.data_path()``, which
    reads ``env.HALO_DATA_ROOT`` at CALL time — so the pin is made deterministic by *setting* that
    root for the duration of the call, not by rewriting the result afterwards. Rewriting cannot
    work: a scratch root of ``/`` (what the documented docker recipe yields on a host whose large
    volume is the root filesystem) is a prefix of every unrelated absolute default as well.
    """
    with mock.patch.object(env, "HALO_DATA_ROOT", "<data_root>"):
        out = {}
        for f in dataclasses.fields(cls):
            if f.default is not dataclasses.MISSING:
                out[f.name] = repr(f.default)
            elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
                out[f.name] = "factory:" + repr(f.default_factory())
            else:
                out[f.name] = "<required>"
        return out


@pytest.mark.parametrize("cls_name", sorted(_EXPECTED))
def test_fields_and_defaults_unchanged(cls_name):
    actual = _field_defaults(_CLASSES[cls_name])
    expected = _EXPECTED[cls_name]
    assert actual == expected, (
        f"{cls_name} field surface drifted.\n"
        f"missing: {sorted(set(expected) - set(actual))}\n"
        f"added: {sorted(set(actual) - set(expected))}\n"
        f"re-defaulted: { {k: (expected[k], actual[k]) for k in set(expected) & set(actual) if expected[k] != actual[k]} }"
    )


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
