#!/usr/bin/env python
"""Smoke: `python <script> --help` works for every config-driven script.

``--help`` is the documented way to see a script's real flag surface (``agent-docs/reference/scripts-reference.md``),
and it is the one path no other test walks: the parser is built from the script's dataclass tuple, so a
field whose metadata/annotation argparse cannot render (a bare ``dict`` default, a help string with a stray
``%``, two dataclasses claiming one flag) breaks ``--help`` for that script alone while training still runs.
A defect in a shared dataclass breaks it on every script that parses it at once.

Each script runs in a fresh subprocess — argparse's help path exits the interpreter, and the parser is
only built inside ``main()``. The set is scanned from the tree, so a new script is covered on arrival,
and running ``--help`` executes the whole module body, so this also covers plain importability.
Each subprocess pays a full torch/transformers import (~30 s).

The `halo run` tools are not config-driven and stay out of that sweep; they are pinned here at the
weaker bar their price allows — every one of them still imports.

Run:
    python tests/cpu/config/test_script_help.py
    pytest -m cpu tests/cpu/config/test_script_help.py
"""

import importlib
import logging
import os
import pathlib
import subprocess
import sys

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
_SCRIPTS_DIR = _REPO_ROOT / "scripts"
_SCRIPTS = sorted(
    path
    for path in _SCRIPTS_DIR.rglob("*.py")
    if "H4ArgumentParser" in path.read_text(encoding="utf-8") and path.name != "__init__.py"
)
# The `halo run` tools: runnable, but built on argparse, so the sweep above never reaches them.
# `diagrams/` is excluded — its generators import a sibling style module off their own directory.
_TOOLS = sorted(
    path
    for path in _SCRIPTS_DIR.rglob("*.py")
    if path not in _SCRIPTS and "diagrams" not in path.parts and "__main__" in path.read_text(encoding="utf-8")
)


def _help_in_subprocess(script: pathlib.Path) -> subprocess.CompletedProcess:
    # PYTHONPATH pinned to THIS tree: the training images bake a repo copy at /workspace and put it
    # on PYTHONPATH, so a subprocess started from any other checkout would parse that copy's args
    # and pass vacuously.
    return subprocess.run(
        [sys.executable, str(script), "--help"],
        capture_output=True,
        text=True,
        cwd=_REPO_ROOT,
        env={**os.environ, "PYTHONPATH": str(_REPO_ROOT)},
        timeout=600,
    )


@pytest.mark.parametrize("script", _SCRIPTS, ids=[str(p.relative_to(_SCRIPTS_DIR)) for p in _SCRIPTS])
def test_script_help_exits_zero(script: pathlib.Path):
    result = _help_in_subprocess(script)
    assert result.returncode == 0, (
        f"{script.relative_to(_SCRIPTS_DIR)} --help exited {result.returncode}:\n{result.stderr[-2000:]}"
    )
    assert "--output_dir" in result.stdout, f"{script.relative_to(_SCRIPTS_DIR)} --help printed no flag list"


@pytest.fixture
def pristine_root_logging():
    """A tool configures the root logger at import (``configure_cli_logging``, ``force=True``), which
    would otherwise strip pytest's own handlers for the rest of the worker."""
    root = logging.getLogger()
    handlers, level = root.handlers[:], root.level
    yield
    root.handlers[:] = handlers
    root.setLevel(level)


@pytest.mark.parametrize("tool", _TOOLS, ids=[str(p.relative_to(_SCRIPTS_DIR)) for p in _TOOLS])
def test_every_tool_script_imports(tool: pathlib.Path, pristine_root_logging):
    """The tools `halo run` indexes must at least import: most are driven by no other test, so a
    `src` module moved out from under one breaks it silently until an operator runs it. In-process,
    unlike the subprocess sweep above — enough to catch a stale import, at seconds instead of 30 s
    a script."""
    importlib.import_module(".".join(tool.relative_to(_REPO_ROOT).with_suffix("").parts))


def test_the_script_scan_is_not_vacuous():
    """Anti-vacuity: both parametrizations are generated by a tree scan, so a scan that matched
    nothing — the marker string renamed, ``scripts/`` relaid out — would collect zero cases and
    report green while covering no script at all."""
    assert len(_SCRIPTS) >= 10, f"only {len(_SCRIPTS)} H4ArgumentParser scripts found under {_SCRIPTS_DIR}"
    assert len(_TOOLS) >= 20, f"only {len(_TOOLS)} argparse tools found under {_SCRIPTS_DIR}"


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
